import * as tableHelpers from './tableHelpers'

export { default as CustomMetadataFieldComponent } from './CustomMetadataFieldComponent'
export { default as FigureLabelGenerator } from './FigureLabelGenerator'
export { default as FigureManager } from './FigureManager'
export { default as FootnoteManager } from './FootnoteManager'
export * from './nodeHelpers'
export { default as NumberedLabelGenerator } from './NumberedLabelGenerator'
export { default as ReferenceManager } from './ReferenceManager'
export { tableHelpers }
export { default as TableComponent } from './TableComponent'
export { default as TableEditing } from './TableEditing'
export { default as TableManager } from './TableManager'
export { default as updateEntityChildArray } from './updateEntityChildArray'
export * from './xrefHelpers'
